In [23]:
import numpy as np
import os
os.listdir()

['.ipynb_checkpoints',
 'Image-conversion.ipynb',
 'newsmallgrey.png',
 'numpy-arrays-2.png',
 'numpy-arrays.png',
 'Numpy.ipynb',
 'readme.md',
 'smallgray.png']

In [ ]:
# pip install opencv-python 
import cv2 

### Reading images in terms of numbers

In [11]:
im_g = cv2.imread('smallgray.png', 0) # 0 for grey, 1 for RGB representation
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

### Writing images from numbers

In [14]:
cv2.imwrite("newsmallgrey.png", im_g)

True

### Indexing, slicing and iteration

In [15]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [16]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [17]:
# transpose
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [19]:
# access to values of arrays one by one
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


### Stacking / concatinating and splitting numpy arrays

In [56]:
ims = np.hstack((im_g, im_g))
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [57]:
lst2 = np.hsplit(ims,2)
lst2

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [58]:
# stack vertically
ims = np.vstack((im_g, im_g))
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [59]:
lst = np.hsplit(ims,5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [60]:
type(lst)

list

In [61]:
lst[0]

array([[187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8)