In [4]:
import numpy as np

In [5]:
n = np.arange(27)

In [6]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [7]:
type(n)

numpy.ndarray

<img src="numpy-arrays.png" width="80%", height="80%"> 

<hr>

<img src="numpy-arrays-2.png">

### 1-dimensional array

In [11]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### 2-dimensional array

In [10]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

### 3-dimensional array

In [13]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
type(n)

numpy.ndarray

### converting a list into numpy array

In [17]:
m=np.asarray([[1,2,3],[],[]])
m

array([list([1, 2, 3]), list([]), list([])], dtype=object)